streams:
  main: "exec:libcamera-vid -t 0 --inline -o -"

api:
  listen: ":1984"    # default ":1984", HTTP API port ("" - disabled)
  username: "admin"  # default "", Basic auth for WebUI
  password: "pass"   # default "", Basic auth for WebUI
  base_path: ""  # default "", API prefix for serve on suburl (/api => /rtc/api)
  static_dir: ""  # default "", folder for static files (custom web interface)
  origin: "*"        # default "", allow CORS requests (only * supported)
  tls_listen: ":443" # default "", enable HTTPS server
  tls_cert: "./certs/MyCertificate.crt"        # default "", PEM-encoded fullchain certificate for HTTPS
  tls_key: "./certs/MyKey.key"         # default "", PEM-encoded private key for HTTPS
  unix_listen: "/tmp/go2rtc.sock"  # default "", unix socket listener for API

# publish:
#   main:
#   - rtmps://xxx.rtmp.youtube.com/live2/<stream-key>

rtsp:
  listen: ":8554"
  default_query: "video"
